### ISSUE TITLE
Sort userlist after rank and alphabetical

### ISSUE THREAD

**Issue by maxaudron** [r-lmr/lmrdashboard#45]
Sort the userlist after rank and alphabetical as a fallback, like most IRC clients do.

```
1. @
2. %
3. +
4. 
```

**Comment by LoLei** [comment]
Done in https://github.com/aboft/lmrdashboard/commit/c3ccc6d7210c72d5cc1741a3d5274842b41ebdbd

The only downside is that that is done on each join/part but for all users. So all users are sorted whenever one joins or leaves. The sorting is kept light by using a sorted set. Still, the underlying flaw comes from just **sending** all users on every join/part. This could be updated by just sending the user delta (i.e. just send the one(s) who joined/parted), and then inserting that one in the already sorted list in the frontend, instead of always completely replacing the existing list in the frontend. But it's fine for now, as there are only about 200 users anyway.
