### ISSUE TITLE
Colon and wrong roles in nick list

### ISSUE THREAD

**Issue by LoLei** [r-lmr/lmrdashboard#74]
![lmrissue1](https://user-images.githubusercontent.com/9076894/104623772-fcb70980-5692-11eb-8db2-20dceb825a9a.png)
![lmrissue2](https://user-images.githubusercontent.com/9076894/104623828-0c365280-5693-11eb-8e57-06acedb55c6b.png)

As can be seen in the images, sometimes there is a colon (`:`) in front of the names, and also the roles are not correct for all users. (For instance mine is missing.)

**Comment by maxaudron** [comment]
So basically the parser is just straight up wrong:
https://github.com/aboft/lmrdashboard/blob/50e75ce574559e927031b919595bea3abebef229/backend/irc/IrcMessageProcessor.ts#L58

You should be looking for a second colon and take everything behind is in as one parameter.
And this in turn leads to you having to stitch them together here:
https://github.com/aboft/lmrdashboard/blob/50e75ce574559e927031b919595bea3abebef229/backend/irc/IrcMessageProcessor.ts#L173

and also messages can be significantly longer than 256... in IRCv2 the whole PRIVMSG thing can have a max length of 512.

**Comment by aboft** [comment]
@maxaudron @LoLei just as an FYI that line 58 you tagged is ONLY for ping responses.

**Comment by LoLei** [comment]
@aboft Maybe we should add a comment there then or split the `parseMessage` up into two informatively named functions.
Also SBL is missing you on the channel.

**Comment by aboft** [comment]
@LoLei @maxaudron the actual bug comes from this line which could be avoided by parsing a second ':' like audron stated but also will be mitigated by removing the colon from the user variable.

https://github.com/aboft/lmrdashboard/blob/50e75ce574559e927031b919595bea3abebef229/backend/irc/IrcMessageProcessor.ts#L95

This could be changed to user.replace(':','') or user.slice(1) or whichever other possibility to your liking.

https://github.com/aboft/lmrdashboard/blob/50e75ce574559e927031b919595bea3abebef229/backend/irc/IrcMessageProcessor.ts#L119

ircMessage.params are these values as an example

`[ '#aboftytest', '+o', ':aboft' ]`
